versions:
  "1.1.0":
    released_at: 2026-01-15T14:20:00Z
    matchers:
      - matcher_type: country
        matcher_value: GB
        severity: red
      - matcher_type: default
        severity: yellow
  "1.2.0":
    released_at: 2026-01-22T10:30:00Z
    matchers:
      - matcher_type: location_hash
        matcher_value: 5feceb66ffc86f38d952786c6d696c79c2dbc239dd4e91b46729d73a27fb57e9
        severity: red
      - matcher_type: country
        matcher_value: US
        severity: yellow
      - matcher_type: default
        severity: green
  "1.9.0":
    released_at: 2026-02-25T15:00:00Z
    matchers:
      - matcher_type: default
        severity: green
  "1.10.0":
    released_at: 2026-03-02T15:00:00Z
    matchers:
      - matcher_type: default
        severity: green
  "23.59.59":
    released_at: 2026-03-03T14:00:00Z
    matchers:
      - matcher_type: default
        severity: green
